[workspace]
members = ["lib", "ports", "test_utils", "web"]
resolver = "2"

[workspace.dependencies]
pretty_assertions = "1.4.0"
arbtest = "0.3.1"
arbitrary = {version = "1.4.1", features = ["derive"]}
